export default {
    ROW_HEIGHT: 40,
    NUM_ROWS: 12,
    ANIMATION_DURATION: 200,
    INDENT: 32,
    LEFT_MARGIN: 12,
    ICON_SIZE: 24,
    TREE_LINES: '1px solid rgba(0,0,0,.07)',
    DISABLE_ANIMATION: false,
    OVERLAY_ANIMATION_DURATION: 300,
    FAIL_RATE: .3,
    ERROR_MODAL_HEIGHT: 250,
}